version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  build:
    commands:
      - echo Build Docker image...
      - docker build -t my-app .
      - echo Save Docker image as tar file...
      - docker save my-app -o my-app.tar
artifacts:
  files:
    - my-app.tar
